USE ECOM;
CREATE TABLE EMP1(
ID INT PRIMARY KEY,
NAME VARCHAR (20),
EMAIL VARCHAR (20),
CITY VARCHAR (20),
DEPT VARCHAR (20),
SALARY BIGINT(10),
AGE INT);


INSERT INTO EMP1 VALUES (1,"MAHESH", "mahesh03@GMAIL","MUMBAI", "IT",10000,20);
INSERT INTO EMP1 VALUES (2,"PRANALV", "PRANAV3@GMAIL","MUMBAI", "IT",5000,20); 
INSERT INTO EMP1 VALUES (3,"YASH ", "YASH@GMAIL","DELHI", "IT",12000,22); 
INSERT INTO EMP1 VALUES (4,"RAJ", "ATHARVA@GMAIL","CHENNAI", "IT",15000,23); 
INSERT INTO EMP1 VALUES (5,"SANYOG", "SANYOGI@GMAIL","PUNE", "BANKING",18000,25); 
INSERT INTO EMP1 VALUES (6,"AMIT ", "AMIT@GMAIL","BANGLORE", "IT",25000,28); 
INSERT INTO EMP1 VALUES (7,"SANKET", "SANKET@GMAIL","PUNE", "BANKING",100000,21); 
INSERT INTO EMP1 VALUES (8,"RAM", "RAM04@GMAIL","PUNE", "BANKING",35000,21); 


ALTER TABLE EMP1
ADD SIRNAME VARCHAR(20);

ALTER TABLE EMP1
MODIFY COLUMN EMAIL VARCHAR(40);

ALTER TABLE EMP1
DROP COLUMN SIRNAME;

ALTER TABLE EMP1
RENAME COLUMN NAME TO  FIRST_NAME;

DELETE FROM EMP1 WHERE ID=1;

TRUNCATE TABLE EMP1;

DROP TABLE EMP1;

SELECT * FROM EMP
WHERE CITY IN('MUMBAI','BANGLORE');

SELECT * FROM EMP
WHERE AGE > 18;

SELECT * FROM EMP
WHERE id = 1 or id = 2;

SELECT count(ID) FROM EMP;

SELECT count(ID) FROM EMP1 
WHERE SALARY >11000;

SELECT sum(SALARY) 
AS "TOTAL SALARY"
FROM EMP1;

SELECT avg(SALARY)
AS "AVERAGE SALARY"
FROM EMP1;

SELECT max(SALARY) FROM EMP1;

SELECT min(SALARY) FROM EMP1;


